# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_aubiowrapper', [dirname(__file__)])
        except ImportError:
            import _aubiowrapper
            return _aubiowrapper
        if fp is not None:
            try:
                _mod = imp.load_module('_aubiowrapper', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _aubiowrapper = swig_import_helper()
    del swig_import_helper
else:
    import _aubiowrapper
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0



def new_fvec(*args):
  return _aubiowrapper.new_fvec(*args)
new_fvec = _aubiowrapper.new_fvec

def del_fvec(*args):
  return _aubiowrapper.del_fvec(*args)
del_fvec = _aubiowrapper.del_fvec

def fvec_read_sample(*args):
  return _aubiowrapper.fvec_read_sample(*args)
fvec_read_sample = _aubiowrapper.fvec_read_sample

def fvec_write_sample(*args):
  return _aubiowrapper.fvec_write_sample(*args)
fvec_write_sample = _aubiowrapper.fvec_write_sample

def fvec_get_channel(*args):
  return _aubiowrapper.fvec_get_channel(*args)
fvec_get_channel = _aubiowrapper.fvec_get_channel

def fvec_put_channel(*args):
  return _aubiowrapper.fvec_put_channel(*args)
fvec_put_channel = _aubiowrapper.fvec_put_channel

def fvec_get_data(*args):
  return _aubiowrapper.fvec_get_data(*args)
fvec_get_data = _aubiowrapper.fvec_get_data

def new_cvec(*args):
  return _aubiowrapper.new_cvec(*args)
new_cvec = _aubiowrapper.new_cvec

def del_cvec(*args):
  return _aubiowrapper.del_cvec(*args)
del_cvec = _aubiowrapper.del_cvec

def cvec_write_norm(*args):
  return _aubiowrapper.cvec_write_norm(*args)
cvec_write_norm = _aubiowrapper.cvec_write_norm

def cvec_write_phas(*args):
  return _aubiowrapper.cvec_write_phas(*args)
cvec_write_phas = _aubiowrapper.cvec_write_phas

def cvec_read_norm(*args):
  return _aubiowrapper.cvec_read_norm(*args)
cvec_read_norm = _aubiowrapper.cvec_read_norm

def cvec_read_phas(*args):
  return _aubiowrapper.cvec_read_phas(*args)
cvec_read_phas = _aubiowrapper.cvec_read_phas

def cvec_put_norm_channel(*args):
  return _aubiowrapper.cvec_put_norm_channel(*args)
cvec_put_norm_channel = _aubiowrapper.cvec_put_norm_channel

def cvec_put_phas_channel(*args):
  return _aubiowrapper.cvec_put_phas_channel(*args)
cvec_put_phas_channel = _aubiowrapper.cvec_put_phas_channel

def cvec_get_norm_channel(*args):
  return _aubiowrapper.cvec_get_norm_channel(*args)
cvec_get_norm_channel = _aubiowrapper.cvec_get_norm_channel

def cvec_get_phas_channel(*args):
  return _aubiowrapper.cvec_get_phas_channel(*args)
cvec_get_phas_channel = _aubiowrapper.cvec_get_phas_channel

def cvec_get_norm(*args):
  return _aubiowrapper.cvec_get_norm(*args)
cvec_get_norm = _aubiowrapper.cvec_get_norm

def cvec_get_phas(*args):
  return _aubiowrapper.cvec_get_phas(*args)
cvec_get_phas = _aubiowrapper.cvec_get_phas

def new_aubio_sndfile_ro(*args):
  return _aubiowrapper.new_aubio_sndfile_ro(*args)
new_aubio_sndfile_ro = _aubiowrapper.new_aubio_sndfile_ro

def new_aubio_sndfile_wo(*args):
  return _aubiowrapper.new_aubio_sndfile_wo(*args)
new_aubio_sndfile_wo = _aubiowrapper.new_aubio_sndfile_wo

def aubio_sndfile_info(*args):
  return _aubiowrapper.aubio_sndfile_info(*args)
aubio_sndfile_info = _aubiowrapper.aubio_sndfile_info

def aubio_sndfile_write(*args):
  return _aubiowrapper.aubio_sndfile_write(*args)
aubio_sndfile_write = _aubiowrapper.aubio_sndfile_write

def aubio_sndfile_read(*args):
  return _aubiowrapper.aubio_sndfile_read(*args)
aubio_sndfile_read = _aubiowrapper.aubio_sndfile_read

def del_aubio_sndfile(*args):
  return _aubiowrapper.del_aubio_sndfile(*args)
del_aubio_sndfile = _aubiowrapper.del_aubio_sndfile

def aubio_sndfile_channels(*args):
  return _aubiowrapper.aubio_sndfile_channels(*args)
aubio_sndfile_channels = _aubiowrapper.aubio_sndfile_channels

def aubio_sndfile_samplerate(*args):
  return _aubiowrapper.aubio_sndfile_samplerate(*args)
aubio_sndfile_samplerate = _aubiowrapper.aubio_sndfile_samplerate

def aubio_fft_getnorm(*args):
  return _aubiowrapper.aubio_fft_getnorm(*args)
aubio_fft_getnorm = _aubiowrapper.aubio_fft_getnorm

def aubio_fft_getphas(*args):
  return _aubiowrapper.aubio_fft_getphas(*args)
aubio_fft_getphas = _aubiowrapper.aubio_fft_getphas

def new_aubio_mfft(*args):
  return _aubiowrapper.new_aubio_mfft(*args)
new_aubio_mfft = _aubiowrapper.new_aubio_mfft

def aubio_mfft_do(*args):
  return _aubiowrapper.aubio_mfft_do(*args)
aubio_mfft_do = _aubiowrapper.aubio_mfft_do

def aubio_mfft_rdo(*args):
  return _aubiowrapper.aubio_mfft_rdo(*args)
aubio_mfft_rdo = _aubiowrapper.aubio_mfft_rdo

def del_aubio_mfft(*args):
  return _aubiowrapper.del_aubio_mfft(*args)
del_aubio_mfft = _aubiowrapper.del_aubio_mfft

def new_aubio_filter(*args):
  return _aubiowrapper.new_aubio_filter(*args)
new_aubio_filter = _aubiowrapper.new_aubio_filter

def new_aubio_adsgn_filter(*args):
  return _aubiowrapper.new_aubio_adsgn_filter(*args)
new_aubio_adsgn_filter = _aubiowrapper.new_aubio_adsgn_filter

def new_aubio_cdsgn_filter(*args):
  return _aubiowrapper.new_aubio_cdsgn_filter(*args)
new_aubio_cdsgn_filter = _aubiowrapper.new_aubio_cdsgn_filter

def aubio_filter_do(*args):
  return _aubiowrapper.aubio_filter_do(*args)
aubio_filter_do = _aubiowrapper.aubio_filter_do

def aubio_filter_do_outplace(*args):
  return _aubiowrapper.aubio_filter_do_outplace(*args)
aubio_filter_do_outplace = _aubiowrapper.aubio_filter_do_outplace

def aubio_filter_do_filtfilt(*args):
  return _aubiowrapper.aubio_filter_do_filtfilt(*args)
aubio_filter_do_filtfilt = _aubiowrapper.aubio_filter_do_filtfilt

def new_aubio_biquad(*args):
  return _aubiowrapper.new_aubio_biquad(*args)
new_aubio_biquad = _aubiowrapper.new_aubio_biquad

def aubio_biquad_do(*args):
  return _aubiowrapper.aubio_biquad_do(*args)
aubio_biquad_do = _aubiowrapper.aubio_biquad_do

def aubio_biquad_do_filtfilt(*args):
  return _aubiowrapper.aubio_biquad_do_filtfilt(*args)
aubio_biquad_do_filtfilt = _aubiowrapper.aubio_biquad_do_filtfilt

def new_aubio_hist(*args):
  return _aubiowrapper.new_aubio_hist(*args)
new_aubio_hist = _aubiowrapper.new_aubio_hist

def del_aubio_hist(*args):
  return _aubiowrapper.del_aubio_hist(*args)
del_aubio_hist = _aubiowrapper.del_aubio_hist

def aubio_hist_do(*args):
  return _aubiowrapper.aubio_hist_do(*args)
aubio_hist_do = _aubiowrapper.aubio_hist_do

def aubio_hist_do_notnull(*args):
  return _aubiowrapper.aubio_hist_do_notnull(*args)
aubio_hist_do_notnull = _aubiowrapper.aubio_hist_do_notnull

def aubio_hist_dyn_notnull(*args):
  return _aubiowrapper.aubio_hist_dyn_notnull(*args)
aubio_hist_dyn_notnull = _aubiowrapper.aubio_hist_dyn_notnull
aubio_win_rectangle = _aubiowrapper.aubio_win_rectangle
aubio_win_hamming = _aubiowrapper.aubio_win_hamming
aubio_win_hanning = _aubiowrapper.aubio_win_hanning
aubio_win_hanningz = _aubiowrapper.aubio_win_hanningz
aubio_win_blackman = _aubiowrapper.aubio_win_blackman
aubio_win_blackman_harris = _aubiowrapper.aubio_win_blackman_harris
aubio_win_gaussian = _aubiowrapper.aubio_win_gaussian
aubio_win_welch = _aubiowrapper.aubio_win_welch
aubio_win_parzen = _aubiowrapper.aubio_win_parzen

def aubio_window(*args):
  return _aubiowrapper.aubio_window(*args)
aubio_window = _aubiowrapper.aubio_window

def aubio_unwrap2pi(*args):
  return _aubiowrapper.aubio_unwrap2pi(*args)
aubio_unwrap2pi = _aubiowrapper.aubio_unwrap2pi

def vec_mean(*args):
  return _aubiowrapper.vec_mean(*args)
vec_mean = _aubiowrapper.vec_mean

def vec_max(*args):
  return _aubiowrapper.vec_max(*args)
vec_max = _aubiowrapper.vec_max

def vec_min(*args):
  return _aubiowrapper.vec_min(*args)
vec_min = _aubiowrapper.vec_min

def vec_min_elem(*args):
  return _aubiowrapper.vec_min_elem(*args)
vec_min_elem = _aubiowrapper.vec_min_elem

def vec_max_elem(*args):
  return _aubiowrapper.vec_max_elem(*args)
vec_max_elem = _aubiowrapper.vec_max_elem

def vec_shift(*args):
  return _aubiowrapper.vec_shift(*args)
vec_shift = _aubiowrapper.vec_shift

def vec_sum(*args):
  return _aubiowrapper.vec_sum(*args)
vec_sum = _aubiowrapper.vec_sum

def vec_local_energy(*args):
  return _aubiowrapper.vec_local_energy(*args)
vec_local_energy = _aubiowrapper.vec_local_energy

def vec_local_hfc(*args):
  return _aubiowrapper.vec_local_hfc(*args)
vec_local_hfc = _aubiowrapper.vec_local_hfc

def vec_alpha_norm(*args):
  return _aubiowrapper.vec_alpha_norm(*args)
vec_alpha_norm = _aubiowrapper.vec_alpha_norm

def vec_dc_removal(*args):
  return _aubiowrapper.vec_dc_removal(*args)
vec_dc_removal = _aubiowrapper.vec_dc_removal

def vec_alpha_normalise(*args):
  return _aubiowrapper.vec_alpha_normalise(*args)
vec_alpha_normalise = _aubiowrapper.vec_alpha_normalise

def vec_add(*args):
  return _aubiowrapper.vec_add(*args)
vec_add = _aubiowrapper.vec_add

def vec_adapt_thres(*args):
  return _aubiowrapper.vec_adapt_thres(*args)
vec_adapt_thres = _aubiowrapper.vec_adapt_thres

def vec_moving_thres(*args):
  return _aubiowrapper.vec_moving_thres(*args)
vec_moving_thres = _aubiowrapper.vec_moving_thres

def vec_median(*args):
  return _aubiowrapper.vec_median(*args)
vec_median = _aubiowrapper.vec_median

def vec_quadint(*args):
  return _aubiowrapper.vec_quadint(*args)
vec_quadint = _aubiowrapper.vec_quadint

def aubio_quadfrac(*args):
  return _aubiowrapper.aubio_quadfrac(*args)
aubio_quadfrac = _aubiowrapper.aubio_quadfrac

def vec_peakpick(*args):
  return _aubiowrapper.vec_peakpick(*args)
vec_peakpick = _aubiowrapper.vec_peakpick

def aubio_bintomidi(*args):
  return _aubiowrapper.aubio_bintomidi(*args)
aubio_bintomidi = _aubiowrapper.aubio_bintomidi

def aubio_miditobin(*args):
  return _aubiowrapper.aubio_miditobin(*args)
aubio_miditobin = _aubiowrapper.aubio_miditobin

def aubio_bintofreq(*args):
  return _aubiowrapper.aubio_bintofreq(*args)
aubio_bintofreq = _aubiowrapper.aubio_bintofreq

def aubio_freqtobin(*args):
  return _aubiowrapper.aubio_freqtobin(*args)
aubio_freqtobin = _aubiowrapper.aubio_freqtobin

def aubio_freqtomidi(*args):
  return _aubiowrapper.aubio_freqtomidi(*args)
aubio_freqtomidi = _aubiowrapper.aubio_freqtomidi

def aubio_miditofreq(*args):
  return _aubiowrapper.aubio_miditofreq(*args)
aubio_miditofreq = _aubiowrapper.aubio_miditofreq

def aubio_silence_detection(*args):
  return _aubiowrapper.aubio_silence_detection(*args)
aubio_silence_detection = _aubiowrapper.aubio_silence_detection

def aubio_level_detection(*args):
  return _aubiowrapper.aubio_level_detection(*args)
aubio_level_detection = _aubiowrapper.aubio_level_detection

def aubio_autocorr(*args):
  return _aubiowrapper.aubio_autocorr(*args)
aubio_autocorr = _aubiowrapper.aubio_autocorr

def new_aubio_scale(*args):
  return _aubiowrapper.new_aubio_scale(*args)
new_aubio_scale = _aubiowrapper.new_aubio_scale

def aubio_scale_set(*args):
  return _aubiowrapper.aubio_scale_set(*args)
aubio_scale_set = _aubiowrapper.aubio_scale_set

def aubio_scale_do(*args):
  return _aubiowrapper.aubio_scale_do(*args)
aubio_scale_do = _aubiowrapper.aubio_scale_do

def del_aubio_scale(*args):
  return _aubiowrapper.del_aubio_scale(*args)
del_aubio_scale = _aubiowrapper.del_aubio_scale

def new_aubio_resampler(*args):
  return _aubiowrapper.new_aubio_resampler(*args)
new_aubio_resampler = _aubiowrapper.new_aubio_resampler

def aubio_resampler_process(*args):
  return _aubiowrapper.aubio_resampler_process(*args)
aubio_resampler_process = _aubiowrapper.aubio_resampler_process

def del_aubio_resampler(*args):
  return _aubiowrapper.del_aubio_resampler(*args)
del_aubio_resampler = _aubiowrapper.del_aubio_resampler
aubio_onset_energy = _aubiowrapper.aubio_onset_energy
aubio_onset_specdiff = _aubiowrapper.aubio_onset_specdiff
aubio_onset_hfc = _aubiowrapper.aubio_onset_hfc
aubio_onset_complex = _aubiowrapper.aubio_onset_complex
aubio_onset_phase = _aubiowrapper.aubio_onset_phase
aubio_onset_kl = _aubiowrapper.aubio_onset_kl
aubio_onset_mkl = _aubiowrapper.aubio_onset_mkl

def new_aubio_onsetdetection(*args):
  return _aubiowrapper.new_aubio_onsetdetection(*args)
new_aubio_onsetdetection = _aubiowrapper.new_aubio_onsetdetection

def aubio_onsetdetection(*args):
  return _aubiowrapper.aubio_onsetdetection(*args)
aubio_onsetdetection = _aubiowrapper.aubio_onsetdetection

def aubio_onsetdetection_free(*args):
  return _aubiowrapper.aubio_onsetdetection_free(*args)
aubio_onsetdetection_free = _aubiowrapper.aubio_onsetdetection_free

def aubio_onsetdetection_energy(*args):
  return _aubiowrapper.aubio_onsetdetection_energy(*args)
aubio_onsetdetection_energy = _aubiowrapper.aubio_onsetdetection_energy

def aubio_onsetdetection_hfc(*args):
  return _aubiowrapper.aubio_onsetdetection_hfc(*args)
aubio_onsetdetection_hfc = _aubiowrapper.aubio_onsetdetection_hfc

def aubio_onsetdetection_complex(*args):
  return _aubiowrapper.aubio_onsetdetection_complex(*args)
aubio_onsetdetection_complex = _aubiowrapper.aubio_onsetdetection_complex

def aubio_onsetdetection_phase(*args):
  return _aubiowrapper.aubio_onsetdetection_phase(*args)
aubio_onsetdetection_phase = _aubiowrapper.aubio_onsetdetection_phase

def aubio_onsetdetection_specdiff(*args):
  return _aubiowrapper.aubio_onsetdetection_specdiff(*args)
aubio_onsetdetection_specdiff = _aubiowrapper.aubio_onsetdetection_specdiff

def aubio_onsetdetection_kl(*args):
  return _aubiowrapper.aubio_onsetdetection_kl(*args)
aubio_onsetdetection_kl = _aubiowrapper.aubio_onsetdetection_kl

def aubio_onsetdetection_mkl(*args):
  return _aubiowrapper.aubio_onsetdetection_mkl(*args)
aubio_onsetdetection_mkl = _aubiowrapper.aubio_onsetdetection_mkl

def new_aubio_pvoc(*args):
  return _aubiowrapper.new_aubio_pvoc(*args)
new_aubio_pvoc = _aubiowrapper.new_aubio_pvoc

def del_aubio_pvoc(*args):
  return _aubiowrapper.del_aubio_pvoc(*args)
del_aubio_pvoc = _aubiowrapper.del_aubio_pvoc

def aubio_pvoc_do(*args):
  return _aubiowrapper.aubio_pvoc_do(*args)
aubio_pvoc_do = _aubiowrapper.aubio_pvoc_do

def aubio_pvoc_rdo(*args):
  return _aubiowrapper.aubio_pvoc_rdo(*args)
aubio_pvoc_rdo = _aubiowrapper.aubio_pvoc_rdo
aubio_pitch_yin = _aubiowrapper.aubio_pitch_yin
aubio_pitch_mcomb = _aubiowrapper.aubio_pitch_mcomb
aubio_pitch_schmitt = _aubiowrapper.aubio_pitch_schmitt
aubio_pitch_fcomb = _aubiowrapper.aubio_pitch_fcomb
aubio_pitch_yinfft = _aubiowrapper.aubio_pitch_yinfft
aubio_pitchm_freq = _aubiowrapper.aubio_pitchm_freq
aubio_pitchm_midi = _aubiowrapper.aubio_pitchm_midi
aubio_pitchm_cent = _aubiowrapper.aubio_pitchm_cent
aubio_pitchm_bin = _aubiowrapper.aubio_pitchm_bin

def aubio_pitchdetection(*args):
  return _aubiowrapper.aubio_pitchdetection(*args)
aubio_pitchdetection = _aubiowrapper.aubio_pitchdetection

def aubio_pitchdetection_set_yinthresh(*args):
  return _aubiowrapper.aubio_pitchdetection_set_yinthresh(*args)
aubio_pitchdetection_set_yinthresh = _aubiowrapper.aubio_pitchdetection_set_yinthresh

def del_aubio_pitchdetection(*args):
  return _aubiowrapper.del_aubio_pitchdetection(*args)
del_aubio_pitchdetection = _aubiowrapper.del_aubio_pitchdetection

def new_aubio_pitchdetection(*args):
  return _aubiowrapper.new_aubio_pitchdetection(*args)
new_aubio_pitchdetection = _aubiowrapper.new_aubio_pitchdetection

def new_aubio_pitchmcomb(*args):
  return _aubiowrapper.new_aubio_pitchmcomb(*args)
new_aubio_pitchmcomb = _aubiowrapper.new_aubio_pitchmcomb

def aubio_pitchmcomb_detect(*args):
  return _aubiowrapper.aubio_pitchmcomb_detect(*args)
aubio_pitchmcomb_detect = _aubiowrapper.aubio_pitchmcomb_detect

def aubio_pitch_cands(*args):
  return _aubiowrapper.aubio_pitch_cands(*args)
aubio_pitch_cands = _aubiowrapper.aubio_pitch_cands

def del_aubio_pitchmcomb(*args):
  return _aubiowrapper.del_aubio_pitchmcomb(*args)
del_aubio_pitchmcomb = _aubiowrapper.del_aubio_pitchmcomb

def aubio_pitchyin_diff(*args):
  return _aubiowrapper.aubio_pitchyin_diff(*args)
aubio_pitchyin_diff = _aubiowrapper.aubio_pitchyin_diff

def aubio_pitchyin_getcum(*args):
  return _aubiowrapper.aubio_pitchyin_getcum(*args)
aubio_pitchyin_getcum = _aubiowrapper.aubio_pitchyin_getcum

def aubio_pitchyin_getpitch(*args):
  return _aubiowrapper.aubio_pitchyin_getpitch(*args)
aubio_pitchyin_getpitch = _aubiowrapper.aubio_pitchyin_getpitch

def aubio_pitchyin_getpitchfast(*args):
  return _aubiowrapper.aubio_pitchyin_getpitchfast(*args)
aubio_pitchyin_getpitchfast = _aubiowrapper.aubio_pitchyin_getpitchfast

def new_aubio_pitchschmitt(*args):
  return _aubiowrapper.new_aubio_pitchschmitt(*args)
new_aubio_pitchschmitt = _aubiowrapper.new_aubio_pitchschmitt

def aubio_pitchschmitt_detect(*args):
  return _aubiowrapper.aubio_pitchschmitt_detect(*args)
aubio_pitchschmitt_detect = _aubiowrapper.aubio_pitchschmitt_detect

def del_aubio_pitchschmitt(*args):
  return _aubiowrapper.del_aubio_pitchschmitt(*args)
del_aubio_pitchschmitt = _aubiowrapper.del_aubio_pitchschmitt

def new_aubio_pitchfcomb(*args):
  return _aubiowrapper.new_aubio_pitchfcomb(*args)
new_aubio_pitchfcomb = _aubiowrapper.new_aubio_pitchfcomb

def aubio_pitchfcomb_detect(*args):
  return _aubiowrapper.aubio_pitchfcomb_detect(*args)
aubio_pitchfcomb_detect = _aubiowrapper.aubio_pitchfcomb_detect

def del_aubio_pitchfcomb(*args):
  return _aubiowrapper.del_aubio_pitchfcomb(*args)
del_aubio_pitchfcomb = _aubiowrapper.del_aubio_pitchfcomb

def new_aubio_peakpicker(*args):
  return _aubiowrapper.new_aubio_peakpicker(*args)
new_aubio_peakpicker = _aubiowrapper.new_aubio_peakpicker

def aubio_peakpick_pimrt(*args):
  return _aubiowrapper.aubio_peakpick_pimrt(*args)
aubio_peakpick_pimrt = _aubiowrapper.aubio_peakpick_pimrt

def aubio_peakpick_pimrt_getval(*args):
  return _aubiowrapper.aubio_peakpick_pimrt_getval(*args)
aubio_peakpick_pimrt_getval = _aubiowrapper.aubio_peakpick_pimrt_getval

def aubio_peakpick_pimrt_wt(*args):
  return _aubiowrapper.aubio_peakpick_pimrt_wt(*args)
aubio_peakpick_pimrt_wt = _aubiowrapper.aubio_peakpick_pimrt_wt

def del_aubio_peakpicker(*args):
  return _aubiowrapper.del_aubio_peakpicker(*args)
del_aubio_peakpicker = _aubiowrapper.del_aubio_peakpicker

def new_aubio_tss(*args):
  return _aubiowrapper.new_aubio_tss(*args)
new_aubio_tss = _aubiowrapper.new_aubio_tss

def del_aubio_tss(*args):
  return _aubiowrapper.del_aubio_tss(*args)
del_aubio_tss = _aubiowrapper.del_aubio_tss

def aubio_tss_do(*args):
  return _aubiowrapper.aubio_tss_do(*args)
aubio_tss_do = _aubiowrapper.aubio_tss_do

def new_aubio_beattracking(*args):
  return _aubiowrapper.new_aubio_beattracking(*args)
new_aubio_beattracking = _aubiowrapper.new_aubio_beattracking

def aubio_beattracking_do(*args):
  return _aubiowrapper.aubio_beattracking_do(*args)
aubio_beattracking_do = _aubiowrapper.aubio_beattracking_do

def del_aubio_beattracking(*args):
  return _aubiowrapper.del_aubio_beattracking(*args)
del_aubio_beattracking = _aubiowrapper.del_aubio_beattracking
NOTE_OFF = _aubiowrapper.NOTE_OFF
NOTE_ON = _aubiowrapper.NOTE_ON
KEY_PRESSURE = _aubiowrapper.KEY_PRESSURE
CONTROL_CHANGE = _aubiowrapper.CONTROL_CHANGE
PROGRAM_CHANGE = _aubiowrapper.PROGRAM_CHANGE
CHANNEL_PRESSURE = _aubiowrapper.CHANNEL_PRESSURE
PITCH_BEND = _aubiowrapper.PITCH_BEND
MIDI_SYSEX = _aubiowrapper.MIDI_SYSEX
MIDI_TIME_CODE = _aubiowrapper.MIDI_TIME_CODE
MIDI_SONG_POSITION = _aubiowrapper.MIDI_SONG_POSITION
MIDI_SONG_SELECT = _aubiowrapper.MIDI_SONG_SELECT
MIDI_TUNE_REQUEST = _aubiowrapper.MIDI_TUNE_REQUEST
MIDI_EOX = _aubiowrapper.MIDI_EOX
MIDI_SYNC = _aubiowrapper.MIDI_SYNC
MIDI_TICK = _aubiowrapper.MIDI_TICK
MIDI_START = _aubiowrapper.MIDI_START
MIDI_CONTINUE = _aubiowrapper.MIDI_CONTINUE
MIDI_STOP = _aubiowrapper.MIDI_STOP
MIDI_ACTIVE_SENSING = _aubiowrapper.MIDI_ACTIVE_SENSING
MIDI_SYSTEM_RESET = _aubiowrapper.MIDI_SYSTEM_RESET
MIDI_META_EVENT = _aubiowrapper.MIDI_META_EVENT
BANK_SELECT_MSB = _aubiowrapper.BANK_SELECT_MSB
MODULATION_MSB = _aubiowrapper.MODULATION_MSB
BREATH_MSB = _aubiowrapper.BREATH_MSB
FOOT_MSB = _aubiowrapper.FOOT_MSB
PORTAMENTO_TIME_MSB = _aubiowrapper.PORTAMENTO_TIME_MSB
DATA_ENTRY_MSB = _aubiowrapper.DATA_ENTRY_MSB
VOLUME_MSB = _aubiowrapper.VOLUME_MSB
BALANCE_MSB = _aubiowrapper.BALANCE_MSB
PAN_MSB = _aubiowrapper.PAN_MSB
EXPRESSION_MSB = _aubiowrapper.EXPRESSION_MSB
EFFECTS1_MSB = _aubiowrapper.EFFECTS1_MSB
EFFECTS2_MSB = _aubiowrapper.EFFECTS2_MSB
GPC1_MSB = _aubiowrapper.GPC1_MSB
GPC2_MSB = _aubiowrapper.GPC2_MSB
GPC3_MSB = _aubiowrapper.GPC3_MSB
GPC4_MSB = _aubiowrapper.GPC4_MSB
BANK_SELECT_LSB = _aubiowrapper.BANK_SELECT_LSB
MODULATION_WHEEL_LSB = _aubiowrapper.MODULATION_WHEEL_LSB
BREATH_LSB = _aubiowrapper.BREATH_LSB
FOOT_LSB = _aubiowrapper.FOOT_LSB
PORTAMENTO_TIME_LSB = _aubiowrapper.PORTAMENTO_TIME_LSB
DATA_ENTRY_LSB = _aubiowrapper.DATA_ENTRY_LSB
VOLUME_LSB = _aubiowrapper.VOLUME_LSB
BALANCE_LSB = _aubiowrapper.BALANCE_LSB
PAN_LSB = _aubiowrapper.PAN_LSB
EXPRESSION_LSB = _aubiowrapper.EXPRESSION_LSB
EFFECTS1_LSB = _aubiowrapper.EFFECTS1_LSB
EFFECTS2_LSB = _aubiowrapper.EFFECTS2_LSB
GPC1_LSB = _aubiowrapper.GPC1_LSB
GPC2_LSB = _aubiowrapper.GPC2_LSB
GPC3_LSB = _aubiowrapper.GPC3_LSB
GPC4_LSB = _aubiowrapper.GPC4_LSB
SUSTAIN_SWITCH = _aubiowrapper.SUSTAIN_SWITCH
PORTAMENTO_SWITCH = _aubiowrapper.PORTAMENTO_SWITCH
SOSTENUTO_SWITCH = _aubiowrapper.SOSTENUTO_SWITCH
SOFT_PEDAL_SWITCH = _aubiowrapper.SOFT_PEDAL_SWITCH
LEGATO_SWITCH = _aubiowrapper.LEGATO_SWITCH
HOLD2_SWITCH = _aubiowrapper.HOLD2_SWITCH
SOUND_CTRL1 = _aubiowrapper.SOUND_CTRL1
SOUND_CTRL2 = _aubiowrapper.SOUND_CTRL2
SOUND_CTRL3 = _aubiowrapper.SOUND_CTRL3
SOUND_CTRL4 = _aubiowrapper.SOUND_CTRL4
SOUND_CTRL5 = _aubiowrapper.SOUND_CTRL5
SOUND_CTRL6 = _aubiowrapper.SOUND_CTRL6
SOUND_CTRL7 = _aubiowrapper.SOUND_CTRL7
SOUND_CTRL8 = _aubiowrapper.SOUND_CTRL8
SOUND_CTRL9 = _aubiowrapper.SOUND_CTRL9
SOUND_CTRL10 = _aubiowrapper.SOUND_CTRL10
GPC5 = _aubiowrapper.GPC5
GPC6 = _aubiowrapper.GPC6
GPC7 = _aubiowrapper.GPC7
GPC8 = _aubiowrapper.GPC8
PORTAMENTO_CTRL = _aubiowrapper.PORTAMENTO_CTRL
EFFECTS_DEPTH1 = _aubiowrapper.EFFECTS_DEPTH1
EFFECTS_DEPTH2 = _aubiowrapper.EFFECTS_DEPTH2
EFFECTS_DEPTH3 = _aubiowrapper.EFFECTS_DEPTH3
EFFECTS_DEPTH4 = _aubiowrapper.EFFECTS_DEPTH4
EFFECTS_DEPTH5 = _aubiowrapper.EFFECTS_DEPTH5
DATA_ENTRY_INCR = _aubiowrapper.DATA_ENTRY_INCR
DATA_ENTRY_DECR = _aubiowrapper.DATA_ENTRY_DECR
NRPN_LSB = _aubiowrapper.NRPN_LSB
NRPN_MSB = _aubiowrapper.NRPN_MSB
RPN_LSB = _aubiowrapper.RPN_LSB
RPN_MSB = _aubiowrapper.RPN_MSB
ALL_SOUND_OFF = _aubiowrapper.ALL_SOUND_OFF
ALL_CTRL_OFF = _aubiowrapper.ALL_CTRL_OFF
LOCAL_CONTROL = _aubiowrapper.LOCAL_CONTROL
ALL_NOTES_OFF = _aubiowrapper.ALL_NOTES_OFF
OMNI_OFF = _aubiowrapper.OMNI_OFF
OMNI_ON = _aubiowrapper.OMNI_ON
POLY_OFF = _aubiowrapper.POLY_OFF
POLY_ON = _aubiowrapper.POLY_ON
MIDI_COPYRIGHT = _aubiowrapper.MIDI_COPYRIGHT
MIDI_TRACK_NAME = _aubiowrapper.MIDI_TRACK_NAME
MIDI_INST_NAME = _aubiowrapper.MIDI_INST_NAME
MIDI_LYRIC = _aubiowrapper.MIDI_LYRIC
MIDI_MARKER = _aubiowrapper.MIDI_MARKER
MIDI_CUE_POINT = _aubiowrapper.MIDI_CUE_POINT
MIDI_EOT = _aubiowrapper.MIDI_EOT
MIDI_SET_TEMPO = _aubiowrapper.MIDI_SET_TEMPO
MIDI_SMPTE_OFFSET = _aubiowrapper.MIDI_SMPTE_OFFSET
MIDI_TIME_SIGNATURE = _aubiowrapper.MIDI_TIME_SIGNATURE
MIDI_KEY_SIGNATURE = _aubiowrapper.MIDI_KEY_SIGNATURE
MIDI_SEQUENCER_EVENT = _aubiowrapper.MIDI_SEQUENCER_EVENT
AUBIO_MIDI_PLAYER_READY = _aubiowrapper.AUBIO_MIDI_PLAYER_READY
AUBIO_MIDI_PLAYER_PLAYING = _aubiowrapper.AUBIO_MIDI_PLAYER_PLAYING
AUBIO_MIDI_PLAYER_DONE = _aubiowrapper.AUBIO_MIDI_PLAYER_DONE
AUBIO_MIDI_READY = _aubiowrapper.AUBIO_MIDI_READY
AUBIO_MIDI_LISTENING = _aubiowrapper.AUBIO_MIDI_LISTENING
AUBIO_MIDI_DONE = _aubiowrapper.AUBIO_MIDI_DONE

def new_aubio_midi_event():
  return _aubiowrapper.new_aubio_midi_event()
new_aubio_midi_event = _aubiowrapper.new_aubio_midi_event

def del_aubio_midi_event(*args):
  return _aubiowrapper.del_aubio_midi_event(*args)
del_aubio_midi_event = _aubiowrapper.del_aubio_midi_event

def aubio_midi_event_set_type(*args):
  return _aubiowrapper.aubio_midi_event_set_type(*args)
aubio_midi_event_set_type = _aubiowrapper.aubio_midi_event_set_type

def aubio_midi_event_get_type(*args):
  return _aubiowrapper.aubio_midi_event_get_type(*args)
aubio_midi_event_get_type = _aubiowrapper.aubio_midi_event_get_type

def aubio_midi_event_set_channel(*args):
  return _aubiowrapper.aubio_midi_event_set_channel(*args)
aubio_midi_event_set_channel = _aubiowrapper.aubio_midi_event_set_channel

def aubio_midi_event_get_channel(*args):
  return _aubiowrapper.aubio_midi_event_get_channel(*args)
aubio_midi_event_get_channel = _aubiowrapper.aubio_midi_event_get_channel

def aubio_midi_event_get_key(*args):
  return _aubiowrapper.aubio_midi_event_get_key(*args)
aubio_midi_event_get_key = _aubiowrapper.aubio_midi_event_get_key

def aubio_midi_event_set_key(*args):
  return _aubiowrapper.aubio_midi_event_set_key(*args)
aubio_midi_event_set_key = _aubiowrapper.aubio_midi_event_set_key

def aubio_midi_event_get_velocity(*args):
  return _aubiowrapper.aubio_midi_event_get_velocity(*args)
aubio_midi_event_get_velocity = _aubiowrapper.aubio_midi_event_get_velocity

def aubio_midi_event_set_velocity(*args):
  return _aubiowrapper.aubio_midi_event_set_velocity(*args)
aubio_midi_event_set_velocity = _aubiowrapper.aubio_midi_event_set_velocity

def aubio_midi_event_get_control(*args):
  return _aubiowrapper.aubio_midi_event_get_control(*args)
aubio_midi_event_get_control = _aubiowrapper.aubio_midi_event_get_control

def aubio_midi_event_set_control(*args):
  return _aubiowrapper.aubio_midi_event_set_control(*args)
aubio_midi_event_set_control = _aubiowrapper.aubio_midi_event_set_control

def aubio_midi_event_get_value(*args):
  return _aubiowrapper.aubio_midi_event_get_value(*args)
aubio_midi_event_get_value = _aubiowrapper.aubio_midi_event_get_value

def aubio_midi_event_set_value(*args):
  return _aubiowrapper.aubio_midi_event_set_value(*args)
aubio_midi_event_set_value = _aubiowrapper.aubio_midi_event_set_value

def aubio_midi_event_get_program(*args):
  return _aubiowrapper.aubio_midi_event_get_program(*args)
aubio_midi_event_get_program = _aubiowrapper.aubio_midi_event_get_program

def aubio_midi_event_set_program(*args):
  return _aubiowrapper.aubio_midi_event_set_program(*args)
aubio_midi_event_set_program = _aubiowrapper.aubio_midi_event_set_program

def aubio_midi_event_get_pitch(*args):
  return _aubiowrapper.aubio_midi_event_get_pitch(*args)
aubio_midi_event_get_pitch = _aubiowrapper.aubio_midi_event_get_pitch

def aubio_midi_event_set_pitch(*args):
  return _aubiowrapper.aubio_midi_event_set_pitch(*args)
aubio_midi_event_set_pitch = _aubiowrapper.aubio_midi_event_set_pitch

def aubio_midi_event_length(*args):
  return _aubiowrapper.aubio_midi_event_length(*args)
aubio_midi_event_length = _aubiowrapper.aubio_midi_event_length

def new_aubio_track(*args):
  return _aubiowrapper.new_aubio_track(*args)
new_aubio_track = _aubiowrapper.new_aubio_track

def del_aubio_track(*args):
  return _aubiowrapper.del_aubio_track(*args)
del_aubio_track = _aubiowrapper.del_aubio_track

def aubio_track_set_name(*args):
  return _aubiowrapper.aubio_track_set_name(*args)
aubio_track_set_name = _aubiowrapper.aubio_track_set_name

def aubio_track_get_name(*args):
  return _aubiowrapper.aubio_track_get_name(*args)
aubio_track_get_name = _aubiowrapper.aubio_track_get_name

def aubio_track_add_event(*args):
  return _aubiowrapper.aubio_track_add_event(*args)
aubio_track_add_event = _aubiowrapper.aubio_track_add_event

def aubio_track_first_event(*args):
  return _aubiowrapper.aubio_track_first_event(*args)
aubio_track_first_event = _aubiowrapper.aubio_track_first_event

def aubio_track_next_event(*args):
  return _aubiowrapper.aubio_track_next_event(*args)
aubio_track_next_event = _aubiowrapper.aubio_track_next_event

def aubio_track_get_duration(*args):
  return _aubiowrapper.aubio_track_get_duration(*args)
aubio_track_get_duration = _aubiowrapper.aubio_track_get_duration

def aubio_track_reset(*args):
  return _aubiowrapper.aubio_track_reset(*args)
aubio_track_reset = _aubiowrapper.aubio_track_reset

def aubio_track_count_events(*args):
  return _aubiowrapper.aubio_track_count_events(*args)
aubio_track_count_events = _aubiowrapper.aubio_track_count_events

def new_aubio_midi_player():
  return _aubiowrapper.new_aubio_midi_player()
new_aubio_midi_player = _aubiowrapper.new_aubio_midi_player

def del_aubio_midi_player(*args):
  return _aubiowrapper.del_aubio_midi_player(*args)
del_aubio_midi_player = _aubiowrapper.del_aubio_midi_player

def aubio_midi_player_reset(*args):
  return _aubiowrapper.aubio_midi_player_reset(*args)
aubio_midi_player_reset = _aubiowrapper.aubio_midi_player_reset

def aubio_midi_player_add_track(*args):
  return _aubiowrapper.aubio_midi_player_add_track(*args)
aubio_midi_player_add_track = _aubiowrapper.aubio_midi_player_add_track

def aubio_midi_player_count_tracks(*args):
  return _aubiowrapper.aubio_midi_player_count_tracks(*args)
aubio_midi_player_count_tracks = _aubiowrapper.aubio_midi_player_count_tracks

def aubio_midi_player_get_track(*args):
  return _aubiowrapper.aubio_midi_player_get_track(*args)
aubio_midi_player_get_track = _aubiowrapper.aubio_midi_player_get_track

def aubio_midi_player_add(*args):
  return _aubiowrapper.aubio_midi_player_add(*args)
aubio_midi_player_add = _aubiowrapper.aubio_midi_player_add

def aubio_midi_player_load(*args):
  return _aubiowrapper.aubio_midi_player_load(*args)
aubio_midi_player_load = _aubiowrapper.aubio_midi_player_load

def aubio_midi_player_callback(*args):
  return _aubiowrapper.aubio_midi_player_callback(*args)
aubio_midi_player_callback = _aubiowrapper.aubio_midi_player_callback

def aubio_midi_player_play(*args):
  return _aubiowrapper.aubio_midi_player_play(*args)
aubio_midi_player_play = _aubiowrapper.aubio_midi_player_play

def aubio_midi_player_play_offline(*args):
  return _aubiowrapper.aubio_midi_player_play_offline(*args)
aubio_midi_player_play_offline = _aubiowrapper.aubio_midi_player_play_offline

def aubio_midi_player_stop(*args):
  return _aubiowrapper.aubio_midi_player_stop(*args)
aubio_midi_player_stop = _aubiowrapper.aubio_midi_player_stop

def aubio_midi_player_set_loop(*args):
  return _aubiowrapper.aubio_midi_player_set_loop(*args)
aubio_midi_player_set_loop = _aubiowrapper.aubio_midi_player_set_loop

def aubio_midi_player_set_midi_tempo(*args):
  return _aubiowrapper.aubio_midi_player_set_midi_tempo(*args)
aubio_midi_player_set_midi_tempo = _aubiowrapper.aubio_midi_player_set_midi_tempo

def aubio_midi_player_set_bpm(*args):
  return _aubiowrapper.aubio_midi_player_set_bpm(*args)
aubio_midi_player_set_bpm = _aubiowrapper.aubio_midi_player_set_bpm

def aubio_midi_player_join(*args):
  return _aubiowrapper.aubio_midi_player_join(*args)
aubio_midi_player_join = _aubiowrapper.aubio_midi_player_join

def aubio_track_send_events(*args):
  return _aubiowrapper.aubio_track_send_events(*args)
aubio_track_send_events = _aubiowrapper.aubio_track_send_events

def aubio_midi_send_event(*args):
  return _aubiowrapper.aubio_midi_send_event(*args)
aubio_midi_send_event = _aubiowrapper.aubio_midi_send_event

def new_aubio_midi_parser():
  return _aubiowrapper.new_aubio_midi_parser()
new_aubio_midi_parser = _aubiowrapper.new_aubio_midi_parser

def del_aubio_midi_parser(*args):
  return _aubiowrapper.del_aubio_midi_parser(*args)
del_aubio_midi_parser = _aubiowrapper.del_aubio_midi_parser

def aubio_midi_parser_parse(*args):
  return _aubiowrapper.aubio_midi_parser_parse(*args)
aubio_midi_parser_parse = _aubiowrapper.aubio_midi_parser_parse

def new_aubio_midi_file(*args):
  return _aubiowrapper.new_aubio_midi_file(*args)
new_aubio_midi_file = _aubiowrapper.new_aubio_midi_file

def del_aubio_midi_file(*args):
  return _aubiowrapper.del_aubio_midi_file(*args)
del_aubio_midi_file = _aubiowrapper.del_aubio_midi_file

def aubio_midi_file_read_mthd(*args):
  return _aubiowrapper.aubio_midi_file_read_mthd(*args)
aubio_midi_file_read_mthd = _aubiowrapper.aubio_midi_file_read_mthd

def aubio_midi_file_load_tracks(*args):
  return _aubiowrapper.aubio_midi_file_load_tracks(*args)
aubio_midi_file_load_tracks = _aubiowrapper.aubio_midi_file_load_tracks

def aubio_midi_file_read_track(*args):
  return _aubiowrapper.aubio_midi_file_read_track(*args)
aubio_midi_file_read_track = _aubiowrapper.aubio_midi_file_read_track

def aubio_midi_file_read_event(*args):
  return _aubiowrapper.aubio_midi_file_read_event(*args)
aubio_midi_file_read_event = _aubiowrapper.aubio_midi_file_read_event

def aubio_midi_file_read_varlen(*args):
  return _aubiowrapper.aubio_midi_file_read_varlen(*args)
aubio_midi_file_read_varlen = _aubiowrapper.aubio_midi_file_read_varlen

def aubio_midi_file_getc(*args):
  return _aubiowrapper.aubio_midi_file_getc(*args)
aubio_midi_file_getc = _aubiowrapper.aubio_midi_file_getc

def aubio_midi_file_push(*args):
  return _aubiowrapper.aubio_midi_file_push(*args)
aubio_midi_file_push = _aubiowrapper.aubio_midi_file_push

def aubio_midi_file_read(*args):
  return _aubiowrapper.aubio_midi_file_read(*args)
aubio_midi_file_read = _aubiowrapper.aubio_midi_file_read

def aubio_midi_file_skip(*args):
  return _aubiowrapper.aubio_midi_file_skip(*args)
aubio_midi_file_skip = _aubiowrapper.aubio_midi_file_skip

def aubio_midi_file_read_tracklen(*args):
  return _aubiowrapper.aubio_midi_file_read_tracklen(*args)
aubio_midi_file_read_tracklen = _aubiowrapper.aubio_midi_file_read_tracklen

def aubio_midi_file_eot(*args):
  return _aubiowrapper.aubio_midi_file_eot(*args)
aubio_midi_file_eot = _aubiowrapper.aubio_midi_file_eot

def aubio_midi_file_get_division(*args):
  return _aubiowrapper.aubio_midi_file_get_division(*args)
aubio_midi_file_get_division = _aubiowrapper.aubio_midi_file_get_division

def new_aubio_midi_driver(*args):
  return _aubiowrapper.new_aubio_midi_driver(*args)
new_aubio_midi_driver = _aubiowrapper.new_aubio_midi_driver

def del_aubio_midi_driver(*args):
  return _aubiowrapper.del_aubio_midi_driver(*args)
del_aubio_midi_driver = _aubiowrapper.del_aubio_midi_driver

def aubio_midi_driver_settings(*args):
  return _aubiowrapper.aubio_midi_driver_settings(*args)
aubio_midi_driver_settings = _aubiowrapper.aubio_midi_driver_settings


